<?php

namespace App\Http\Controllers\Voyager;

use App\AudioCategory;
use Dotenv\Validator;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\VoyagerUserController as BaseVoyagerUserController;

class VoyagerAudioController extends BaseVoyagerUserController
{

    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
